version = 0.1
[default.deploy.parameters]
stack_name = "air-conditioner-strategy"
resolve_s3 = true
s3_prefix = "air-conditioner-strategy"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
