AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Propose air conditions configuration

Globals:
  Function:
    Runtime: python3.10
    Timeout: 900

Resources:
  PythonLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyPythonLibrariesLayer
      Description: Python libraries for lambda functions
      ContentUri: src/layer/python/
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.10

  DetectActivities:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/detect_activities/
      Handler: app.lambda_handler
      Layers:
        - !Ref PythonLibrariesLayer
      Events:
        QueryRoom:
          Type: Api
          Properties:
            Path: /rooms/{room_id}/activity
            Method: get
        DataStream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt ActivityKinesisStream.Arn
            StartingPosition: LATEST
            BatchSize: 10
            BisectBatchOnFunctionError: true
            MaximumRetryAttempts: 1
            ParallelizationFactor: 5

  ActivityKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  InvestigateLayouts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/investigate_layouts/
      Handler: app.lambda_handler
      Layers:
        - !Ref PythonLibrariesLayer
      Events:
        QueryFloor:
          Type: Api
          Properties:
            Path: /floors/{floor_id}/layout
            Method: get

  MonitorSensors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/monitor_sensors/
      Handler: app.lambda_handler
      Layers:
        - !Ref PythonLibrariesLayer
      Events:
        QuerySensor:
          Type: Api
          Properties:
            Path: /sensors/{sensor_id}/data
            Method: get
        DataStream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt SensorKinesisStream.Arn
            StartingPosition: LATEST
            BatchSize: 10
            BisectBatchOnFunctionError: true
            MaximumRetryAttempts: 1
            ParallelizationFactor: 5
      Environment:
        Variables:
          SENSOR_DATABASE_TABLE: SensorDatabaseTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SensorDatabaseTable

  SensorKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  SensorDatabaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SensorDatabaseTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ProposeStrategies:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/propose_stategies/
      Handler: app.lambda_handler
      Layers:
        - !Ref PythonLibrariesLayer
      Events:
        QueryFloor:
          Type: Api
          Properties:
            Path: /floors/{floor_id}/strategy
            Method: get

Outputs:
  DetectActivitiesApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/rooms/0/activity"
  ActivityKinesisStreamArn:
    Description: Activity kinesis stream ARN
    Value: !Ref ActivityKinesisStream
  SensorKinesisStreamArn:
    Description: Sensor kinesis stream ARN
    Value: !Ref SensorKinesisStream
