AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Propose air conditions configuration

Globals:
  Function:
    Runtime: python3.10
    Timeout: 900

Resources:
  DetectActivities:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/detect_activities/
      Handler: app.lambda_handler
      Events:
        QueryRoom:
          Type: Api
          Properties:
            Path: /rooms/{room_id}/activity
            Method: get
  InvestigateLayouts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/investigate_layouts/
      Handler: app.lambda_handler
      Events:
        QueryFloor:
          Type: Api
          Properties:
            Path: /floors/{floor_id}/layout
            Method: get
  MonitorSensors:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/monitor_sensors/
      Handler: app.lambda_handler
      Events:
        QuerySensor:
          Type: Api
          Properties:
            Path: /sensors/{sensor_id}
            Method: get
  ProposeStrategies:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/propose_stategies/
      Handler: app.lambda_handler
      Events:
        QueryFloor:
          Type: Api
          Properties:
            Path: /floors/{floor_id}/strategy
            Method: get

Outputs:
  DetectActivitiesApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/rooms/0/activity"
